import type { Metadata } from "next";
import { Playfair_Display, Sora } from "next/font/google";
import "./globals.css";
import { CVProvider } from "@/context/CVContext";
import ThemeToggle from "@/components/ThemeToggle";
import { InterviewProvider } from "@/context/InterviewContext";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${sora.variable} antialiased`}
      >
        <div
          className=" font-sora 
        
        "
        >
          <CVProvider>
            <InterviewProvider>{children}</InterviewProvider>
          </CVProvider>
          <ThemeToggle />
        </div>
      </body>
    </html>
  );
}
