import type { Metadata } from "next";
import { Playfair_Display, Sora } from "next/font/google";
import "./globals.css";
import { CVProvider } from "@/context/CVContext";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const sora = Sora({
  weight: ["400", "600", "700"],
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${sora.variable} antialiased`}
      >
        <div className="font-sora text-zinc-900 dark:text-zinc-50 bg-zinc-50 dark:bg-zinc-800">
          <CVProvider>{children}</CVProvider>
        </div>
      </body>
    </html>
  );
}
